### ISSUE TITLE
Allow for multi-region operation

### ISSUE THREAD

**Issue by thanethomson** [interchainio/got#2]
Right now, the GoT AMI and Terraform scripts are locked to a single AWS region (`us-east-1`). Since this AMI is the base image used by all White Walker and Stark nodes, we need to be able to access this image from more AWS regions.

This would most likely require expanding on the `extras/launcher/terraform.tf` script, and we'll most likely have to find a better way of mapping out the zones in each experiment's `config.toml` file (because we can't force people to have to supply AMI IDs for each region in their `config.toml` files).

**Comment by thanethomson** [comment]
The way I did it in the `tmtestnet` repo is to create a Tendermint module that can be called from the base module depending on the required regions: https://github.com/interchainio/testnets/blob/master/tendermint/terraform/main.tf

Perhaps that approach would help?

**Comment by greg-szabo** [comment]
This is implemented in a more dynamic manner: the nightking will check its own AMI ID, find the AMI name and search for that AMI name in any other region where it needs to build nodes. This is done automatically in Terraform.
The `config.toml` for the experiment can be configured to any of the supported regions. The only restriction is that you need to explicitly state each node's region in the file. (See the `xp2` experiment that puts nodes in different regions.)
